### ISSUE TITLE
GitHub app API query parameter deprecation

### ISSUE THREAD

**Issue by fletchto99** [gitalk/gitalk#343] opened 2020-02-03 23:42 UTC
GitHub is going to be deprecating sending the client ID and client secret as query parameters. Gitalk will need to be updated to use basic authentication. For more information see: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

**Comment by klboke** [comment] 2020-02-04 02:25
都收到通知邮件了

**Comment by AriaLyy** [comment] 2020-02-04 02:52
+1，今天被这个邮件轰炸了

**Comment by AriaLyy** [comment] 2020-02-04 02:53
有老哥知道该怎么解决吗？

**Comment by wangriyu** [comment] 2020-02-04 03:18
+1

**Comment by 40huo** [comment] 2020-02-04 03:19
+1

**Comment by Mabbs** [comment] 2020-02-04 03:20
+1

**Comment by ldzhangyx** [comment] 2020-02-04 03:20
我也收到了，蹲一个解决

**Comment by sparkydogX** [comment] 2020-02-04 03:20
+1

**Comment by L1H0n9Jun** [comment] 2020-02-04 03:30
+1 Mark

**Comment by copperion** [comment] 2020-02-04 03:38
mark, same problem

**Comment by jiangzhonglian** [comment] 2020-02-04 03:48
+1 Mark

**Comment by wizardforcel** [comment] 2020-02-04 03:53
plz modify HTTP requests to put `client_id` in the `Authentication` header.

**Comment by deamwork** [comment] 2020-02-04 04:13
It uses `window.location.href` for Github authorization redirect, so it may need to refactor on how to redirect. [ref](https://github.com/gitalk/gitalk/blob/master/src/gitalk.jsx#L479)
the request is pure query parameters located [at line 160](https://github.com/gitalk/gitalk/blob/master/src/gitalk.jsx#L160)

Right now, the browser can't produce a GET request with a modified header. Only POST can do. So I have no idea how to fix this without 3rd party support(e.g., forward by the backend, etc.)

**Comment by YunYouJun** [comment] 2020-02-04 05:29
Is there any temporary solution?

**Comment by geektutu** [comment] 2020-02-04 06:11
> GitHub is deprecating authentication to the GitHub API using query parameters, such as using a access_token query parameter for OAuth user authentication or a client_id/client_secret query parameter for OAuth application authentication. All authentication to the GitHub API should be done using HTTP basic authentication.

Gitalk should use basic auth to replace client_id/client_secret query parameter.

I open a pull request  [diff](https://github.com/gitalk/gitalk/pull/344/files#diff-b75da62042ff3385546ca75d01d07585) to resolve the issue, about ten lines are modified. And I regenerate [gitalk.min.js](https://github.com/geektutu/hexo-theme-geektutu/blob/master/source/js/gitalk.min.js)

**Follow next steps**

- Goto [accessToken](https://github.com/settings/tokens) to generate a public read-only token
- Use the new [gitalk.min.js](https://github.com/geektutu/hexo-theme-geektutu/blob/master/source/js/gitalk.min.js) to replace the old one
- Config your token in your template

```javascript
const gitalk = new Gitalk({
  clientID: 'GitHub Application Client ID',
  clientSecret: 'GitHub Application Client Secret',
  accessToken: 'Github Personal Access Token',   // here !!!
  repo: 'GitHub repo',
  owner: 'GitHub repo owner',
  admin: ['GitHub repo owner and collaborators, only these guys can initialize github issues'],
  id: location.pathname,      // Ensure uniqueness and length less than 50
  distractionFreeMode: false  // Facebook-like distraction free mode
})
```

**Comment by Mabbs** [comment] 2020-02-04 06:19
> > GitHub is deprecating authentication to the GitHub API using query parameters, such as using a access_token query parameter for OAuth user authentication or a client_id/client_secret query parameter for OAuth application authentication. All authentication to the GitHub API should be done using HTTP basic authentication.
> 
> Gitalk should use basic auth to replace client_id/client_secret query parameter.
> 
> I open a pull request [diff](https://github.com/gitalk/gitalk/pull/344/files#diff-b75da62042ff3385546ca75d01d07585) to resolve the issue, about ten lines are modified. And I regenerate [gitalk.min.js](https://github.com/geektutu/hexo-theme-geektutu/blob/master/source/js/gitalk.min.js). All regenerated files are [here](https://github.com/geektutu/gitalk/tree/master/dist)
> 
> **Follow next steps**
> 
> * Goto [accessToken](https://github.com/settings/tokens) to generate a public read-only token
> * Use the new [gitalk.min.js](https://github.com/geektutu/hexo-theme-geektutu/blob/master/source/js/gitalk.min.js) to replace the old one
> * Config your token in your template
> 
> ```js
> const gitalk = new Gitalk({
>   clientID: 'GitHub Application Client ID',
>   clientSecret: 'GitHub Application Client Secret',
>   accessToken: 'Github Personal Access Token',   // here !!!
>   repo: 'GitHub repo',
>   owner: 'GitHub repo owner',
>   admin: ['GitHub repo owner and collaborators, only these guys can initialize github issues'],
>   id: location.pathname,      // Ensure uniqueness and length less than 50
>   distractionFreeMode: false  // Facebook-like distraction free mode
> })
> ```

How to generate a public read-only token?I just find Access public repositories permission.It's dangerous.

**Comment by geektutu** [comment] 2020-02-04 06:20
@Mabbs 

**About accessToken security**

According to [Understanding scopes for OAuth Apps](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes), if you don't select any scope when generate your access token, the token just grants read-only access to public information.

**Comment by draveness** [comment] 2020-02-04 06:31
> @Mabbs
> 
> **About accessToken security**
> 
> According to [Understanding scopes for OAuth Apps](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes), if you don't select any scope when generating your access token, the token just grants read-only access to public information.
> 
> Here is [my blog](https://geektutu.com/), it works well.
> 
> If you find it dangerous, please tell me to revoke it, thank you.

So is it possible to create a new github account to generate the public access token?

**Comment by geektutu** [comment] 2020-02-04 06:43
@draveness You're right, gitalk uses access token( client secret before) to get higher api rate limit, so any account's access token is ok.

with access token, 5000 per hour

```bash
curl -H "Authorization: token YOUR TOKEN" https://api.github.com/rate_limit
{
  "resources": {
    "core": {
      "limit": 5000,
      "remaining": 4961,
      "reset": 1580799676
    },
...
``` 

without access token, 60 per hour.

```curl
curl https://api.github.com/rate_limit 
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 60,
      "reset": 1580801932
```

see [Rate limiting](https://developer.github.com/v3/#rate-limiting)

**Comment by draveness** [comment] 2020-02-04 06:53
> @draveness You're right, gitalk uses access token( client secret before) to get higher api rate limit, so any account's access token is ok.
> 
> with access token, 5000 requests per hour
> 
> ```shell
> curl -H "Authorization: token YOUR TOKEN" https://api.github.com/rate_limit
> {
>   "resources": {
>     "core": {
>       "limit": 5000,
>       "remaining": 4961,
>       "reset": 1580799676
>     },
> ...
> ```
> 
> without access token, 60 requests per hour.
> 
> ```
> curl https://api.github.com/rate_limit 
> {
>   "resources": {
>     "core": {
>       "limit": 60,
>       "remaining": 60,
>       "reset": 1580801932
> ```
> 
> See [Rate limiting](https://developer.github.com/v3/#rate-limiting)
> 
> **One more thing**
> 
> * For login user, use their own access token that's granted by themselves when login.
> * For anonymous user, use access token configured by you.
> 
> ```js
>     const { owner, repo, id, labels, accessToken } = this.options
>     return axiosGithub.get(`/repos/${owner}/${repo}/issues`, {
>       headers: {
>         Authorization: `token ${this.accessToken || accessToken}`
>       },
>     ...
> ```

Thanks for the detailed explanation.

**Comment by fletchto99** [comment] 2020-02-04 07:13
@geektutu It would probably be better to just use anonymous requests here. Since the API request would be associated with the user's IP instead of your account (for example if they grabbed your PAT and began to abuse it). Since the limit is only used to retrieve comments 60 should be plenty.

**Comment by geektutu** [comment] 2020-02-04 08:04
@fletchto99 Your worry is right. However, many people share the same public IP, eg, through the same gateway of the company, or in some areas where IP is lacking. Each page will cost 2 or more requests. 60 per hour will be used up soon. Probably it'll bring bad experience. I have no idea but to add danger notice to guide people to select nothing when generating PAT.

**Comment by chenbin-353549444** [comment] 2020-02-04 08:18
+1 Mark

**Comment by TRHX** [comment] 2020-02-04 09:00
+1 Mark

**Comment by peanut996** [comment] 2020-02-04 09:01
+1

**Comment by bessyjl** [comment] 2020-02-04 09:20
+1

**Comment by honeyshine75** [comment] 2020-02-04 09:43
+1 Mark

**Comment by q191201771** [comment] 2020-02-04 09:52
mark

**Comment by draveness** [comment] 2020-02-04 09:57
It would be better to click the 👍 in the first comment instead of reply `+1` below. 🙂

**Comment by Liam0205** [comment] 2020-02-04 09:59
> It would be better to click the 👍 in the first comment instead of reply `+1` below. 🙂

yes...

or, one could just click `subscribe` on the right sidebar.

**Comment by geektutu** [comment] 2020-02-04 11:53
@fletchto99 [#344(comment)](https://github.com/gitalk/gitalk/pull/344#issuecomment-581855571), access token is optional, if PAT is not configured, use anonymous requests. And it's compatible with previous version.

- Here is regenerated [gitalk.min.js](https://geektutu.github.io/hexo-theme-geektutu/js/gitalk.min.js)

**Comment by hsiangfeng** [comment] 2020-02-04 14:28
I add to accesstoken and use 1.5.0, but...The problem is still not resolved

this is my [blog](https://hsiangfeng.github.io/)

What am I doing wrong?

**Comment by kb1000fx** [comment] 2020-02-04 14:56
+1 mark

**Comment by geektutu** [comment] 2020-02-04 15:44
@hsiangfeng Your blog still loads gitalk.min.js from `cdn.jsdelivr.net`, the CDN‘s code is still old.
So replace it with [the new one](https://geektutu.github.io/hexo-theme-geektutu/js/gitalk.min.js) and have a try.

**Comment by SmileTM** [comment] 2020-02-04 16:39
so，Hexo blog ，how to solve this problem?

**Comment by RimoChan** [comment] 2020-02-04 16:56
傻逼github，明明說「we'll be sending you this email reminder at most once every 3 days」，結果一天給我發了幾封！

**Comment by SmileTM** [comment] 2020-02-04 17:00
> 傻逼github，明明說「we'll be sending you this email reminder at most once every 3 days」，結果一天給我發了幾封！

笑喷，我github绑了3个邮箱，而且邮箱邮件全部设置转发到指定邮箱。一天差不多就是9封。

**Comment by hsiangfeng** [comment] 2020-02-05 00:44
> @hsiangfeng Your blog still loads gitalk.min.js from `cdn.jsdelivr.net`, the CDN‘s code is still old.
> So replace it with [the new one](https://geektutu.github.io/hexo-theme-geektutu/js/gitalk.min.js) and have a try.

@geektutu  So I need use https://unpkg.com/gitalk? or not use CDN?
Becouse I see CDN version is 1.5.0.

![圖片](https://user-images.githubusercontent.com/19990752/73800466-c53dad00-47f3-11ea-9b7f-6fca3eaec57d.png)

**Comment by geektutu** [comment] 2020-02-05 01:41
Util now it's a temporary solution, so if aren't able to modify your hexo theme, just wait gitalk or the author of the theme that you are using to fix it.

The old one works well except for email bombs.

**Comment by kzhiquan** [comment] 2020-02-05 06:47
+ 1 mark

**Comment by imgradeone** [comment] 2020-02-05 07:28
> 傻逼github，明明說「we'll be sending you this email reminder at most once every 3 days」，結果一天給我發了幾封！

at most 啦 😂

**Comment by yeung66** [comment] 2020-02-05 10:08
关注，我也出现了这个问题

**Comment by removeif** [comment] 2020-02-05 10:51
`蹲一个万全之策.`

**Comment by Mabbs** [comment] 2020-02-05 11:07
> `蹲一个万全之策.`

以我博客的访问量，就geektutu的解决方案感觉已经很完美了

**Comment by hooray** [comment] 2020-02-05 11:07
> > 傻逼github，明明說「we'll be sending you this email reminder at most once every 3 days」，結果一天給我發了幾封！
> 
> 笑喷，我github绑了3个邮箱，而且邮箱邮件全部设置转发到指定邮箱。一天差不多就是9封。

我就一个账号，但今天就收到了近20封

**Comment by RimoChan** [comment] 2020-02-05 11:57
> > 傻逼github，明明說「we'll be sending you this email reminder at most once every 3 days」，結果一天給我發了幾封！
> 
> at most 啦 😂

at most 修飾的是分子 once 不是分母 3 days ，頻率應該變小而不是變大啊。

**Comment by meibin08** [comment] 2020-02-06 02:27
> > GitHub is deprecating authentication to the GitHub API using query parameters, such as using a access_token query parameter for OAuth user authentication or a client_id/client_secret query parameter for OAuth application authentication. All authentication to the GitHub API should be done using HTTP basic authentication.
> 
> Gitalk should use basic auth to replace client_id/client_secret query parameter.
> 
> I open a pull request [diff](https://github.com/gitalk/gitalk/pull/344/files#diff-b75da62042ff3385546ca75d01d07585) to resolve the issue, about ten lines are modified. And I regenerate [gitalk.min.js](https://geektutu.github.io/hexo-theme-geektutu/js/gitalk.min.js). All regenerated files are [here](https://github.com/geektutu/gitalk/tree/master/dist)
> 
> **Follow next steps**
> 
> * Use the new [gitalk.min.js](https://geektutu.github.io/hexo-theme-geektutu/js/gitalk.min.js) to replace the old one
> 
> **If you need higher limit rate**
> 
> * [Optional] Goto [accessToken](https://github.com/settings/tokens) to generate a public read-only token (Don't select any scope)
> * [Optional] Config your token in your template
> 
> ```js
> const gitalk = new Gitalk({
>   clientID: 'GitHub Application Client ID',
>   clientSecret: 'GitHub Application Client Secret',
>   accessToken: 'Github Personal Access Token',   // IMPORTANT !!!
>   repo: 'GitHub repo',
>   owner: 'GitHub repo owner',
>   ...
> })
> ```

我的也收到了，按你的方法，去生成了一个token，不知道还会不会发邮件！

**Comment by Aqua-Dream** [comment] 2020-02-06 07:34
插眼

**Comment by MHuiG** [comment] 2020-02-06 10:51
关注

**Comment by booxood** [comment] 2020-02-06 16:10
不好意思给大家带来了烦恼。

已经合并了 PR #344，发布了 v1.5.1，麻烦大家升级一下版本，并增加配置 `accessToken`。

感谢 @geektutu :clap::clap::clap:

---
Sorry for the trouble.

Has been merged PR #344 and released v1.5.1. Please update the version and add option 'accessToken'.

Thank @geektutu :clap: :clap: :clap:.

**Comment by fletchto99** [comment] 2020-02-06 18:13
I've opened https://github.com/gitalk/gitalk/pull/346 to address the concerns I had expressed in https://github.com/gitalk/gitalk/issues/343#issuecomment-581773838 - I've confirmed with GitHub that sending the `client_id` and `client_secret` as basic auth is a supported flow so I believe this would be the best route forward.

**Comment by qcmoke** [comment] 2020-02-06 19:20
我也遇到了同样的问题，怎么个具体解决呢？

**Closed** 2020-02-07 02:37 UTC

**Comment by booxood** [comment] 2020-02-07 02:58
@qcmoke  更新最新版本，**不用修改配置，确保版本 >= v1.5.2 **。

具体详情可以看 #346。

**Comment by qcmoke** [comment] 2020-02-16 20:50
> @qcmoke 更新最新版本，**不用修改配置，确保版本 >=v1.5.2**。
> 
> 具体详情可以看 #346。

我使用的是如下方式引入的,通过浏览器调试发现确实是版本 >=v1.5.2**了的，但是还是每天会收到github的邮件提醒！请问怎么回事呢？
```html
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
```
调式版本如下图：
![image](https://user-images.githubusercontent.com/30585066/74612483-cbf7e880-5140-11ea-85ba-5208a7404e86.png)

**Comment by MHuiG** [comment] 2020-02-16 23:28
> > @qcmoke 更新最新版本，**不用修改配置，确保版本 >=v1.5.2**。
> > 具体详情可以看 #346。
> 
> 我使用的是如下方式引入的,通过浏览器调试发现确实是版本 >=v1.5.2**了的，但是还是每天会收到github的邮件提醒！请问怎么回事呢？
> 
> ```
> <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
> <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
> ```
> 
> 调式版本如下图：
> ![image](https://user-images.githubusercontent.com/30585066/74612483-cbf7e880-5140-11ea-85ba-5208a7404e86.png)

这可能是因为浏览器缓存或者CDN缓存未刷新的问题，问题缓存可能不在你这里，你的用户没有刷新缓存。

可以尝试将gitalk js和css 保存到本地后引用。

**Comment by minbaby** [comment] 2020-02-17 02:01
> > @qcmoke 更新最新版本，**不用修改配置，确保版本 >=v1.5.2**。
> > 具体详情可以看 #346。
> 
> 我使用的是如下方式引入的,通过浏览器调试发现确实是版本 >=v1.5.2**了的，但是还是每天会收到github的邮件提醒！请问怎么回事呢？
> 
> ```
> <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
> <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
> ```
> 
> 调式版本如下图：
> ![image](https://user-images.githubusercontent.com/30585066/74612483-cbf7e880-5140-11ea-85ba-5208a7404e86.png)

看你图中，引用了两次 gitalk 资源文件，猜测一个是新的，一个是旧的，旧的只要初始化就会发告警邮件。

**Comment by qcmoke** [comment] 2020-02-18 23:04
> > > @qcmoke 更新最新版本，**不用修改配置，确保版本 >=v1.5.2**。
> > > 具体详情可以看 #346。
> > 
> > 
> > 我使用的是如下方式引入的,通过浏览器调试发现确实是版本 >=v1.5.2**了的，但是还是每天会收到github的邮件提醒！请问怎么回事呢？
> > ```
> > <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
> > <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
> > ```
> > 
> > 
> > 调式版本如下图：
> > ![image](https://user-images.githubusercontent.com/30585066/74612483-cbf7e880-5140-11ea-85ba-5208a7404e86.png)
> 
> 看你图中，引用了两次 gitalk 资源文件，猜测一个是新的，一个是旧的，旧的只要初始化就会发告警邮件。

已经解决了，谢谢，是缓存的原因

**Comment by qcmoke** [comment] 2020-02-18 23:05
> > > @qcmoke 更新最新版本，**不用修改配置，确保版本 >=v1.5.2**。
> > > 具体详情可以看 #346。
> > 
> > 
> > 我使用的是如下方式引入的,通过浏览器调试发现确实是版本 >=v1.5.2**了的，但是还是每天会收到github的邮件提醒！请问怎么回事呢？
> > ```
> > <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
> > <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
> > ```
> > 
> > 
> > 调式版本如下图：
> > ![image](https://user-images.githubusercontent.com/30585066/74612483-cbf7e880-5140-11ea-85ba-5208a7404e86.png)
> 
> 看你图中，引用了两次 gitalk 资源文件，猜测一个是新的，一个是旧的，旧的只要初始化就会发告警邮件。

已经解决了，谢谢，是缓存的原因

> > > @qcmoke 更新最新版本，**不用修改配置，确保版本 >=v1.5.2**。
> > > 具体详情可以看 #346。
> > 
> > 
> > 我使用的是如下方式引入的,通过浏览器调试发现确实是版本 >=v1.5.2**了的，但是还是每天会收到github的邮件提醒！请问怎么回事呢？
> > ```
> > <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
> > <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
> > ```
> > 
> > 
> > 调式版本如下图：
> > ![image](https://user-images.githubusercontent.com/30585066/74612483-cbf7e880-5140-11ea-85ba-5208a7404e86.png)
> 
> 这可能是因为浏览器缓存或者CDN缓存未刷新的问题，问题缓存可能不在你这里，你的用户没有刷新缓存。
> 
> 可以尝试将gitalk js和css 保存到本地后引用。
> 
> 或者指定版本号
> 
> ```
> <link rel="stylesheet" href="https://unpkg.com/gitalk@1.6.0/dist/gitalk.css">
> <script src="https://unpkg.com/gitalk@1.6.0/dist/gitalk.min.js"></script>
> ```

已经解决了，谢谢，确实是缓存的原因
